
name: Integration

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main]

jobs:
  unzip:
    runs-on: ubuntu-latest
    name: Unzip
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20.5"

      - name: Build
        run: go build -o biunzip .

      - name: Unzip Sinle File
        run: ./biunzip -f test_data/zip_files/sample.zip

      - name: Unzip Single Encrypted File
        run: ./biunzip -f test_data/zip_files/encrypted_sample.zip -p sample_password

      - name: Unzip Multiple Files
        run: ./biunzip -d test_data/zip_files -c test_data/csv_files/success.csv